#!/bin/sh
#
# Run all dotfiles installers.
set -e

cd "$(dirname "$0")"/..

# find the installers and run them iteratively
find $DOTFILES -name install.sh | while read -r installer; do
	echo "› ${installer}..."
	sh -c "$installer"
done