#!/bin/sh
#
# Run all dotfiles installers.
set -e

echo "Start backup"
$HOME/.dotfiles/scripts/backup
echo "Backup complete"

export DOTFILES="$HOME/.dotfiles"
echo "Setting up dotfiles in $DOTFILES"

echo "copy .zshrc file to $HOME/.zshrc"
cp $HOME/.zshrc $HOME/.zshrc.bak-$(date '+%Y%m%d')
cp $DOTFILES/.zshrc $HOME/.zshrc

cd "$(dirname "$0")"/..

# find the installers and run them iteratively
find $DOTFILES -name install.sh | while read -r installer; do
	echo "› ${installer}..."
	sh -c "$installer"
done

DISP_COLOR="\033[0;32m" #Green color
NO_COLOR="\033[0m" # No Color
echo -e "\n${DISP_COLOR}Installation completed successfully${NO_COLOR}"

DISP_COLOR="\033[0;33m" #Yellow color
echo -e "\n${DISP_COLOR}[Optional] Copy .local_exports, .sandboxrc, .proxy_settings in to your home directory and reload the terminal${NO_COLOR}"

unset timestamp
unset DOTFILES